language: java

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
      - akamen@blackducksoftware.com
      - ekerwin@blackducksoftware.com

install: true
script:
  - mvn clean package -DskipTests
