language: java

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - akamen@blackducksoftware.com
      - ekerwin@blackducksoftware.com
      - rotte@blackducksoftware.com

install: true

script:
  - ./gradlew clean build

after_success:
  - ./gradlew test jacocoTestReport coveralls
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
